version: '3'

services:
  app_local:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - ${APP_PORT}:3000
    volumes:
      - ./src:/app/src
      - ./test:/app/test
    entrypoint: [ "yarn", "start:dev" ]

  db_local:
    image: postgres:14
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
    ports:
      - ${FORWARD_POSTGRES_PORT}:5432
    volumes:
      - pgdata_local:/var/lib/postgresql/data

  redis_local:
    image: redis:alpine
    ports:
      - ${FORWARD_REDIS_PORT}:6379
    volumes:
      - ./redis-data-local:/data
      - ./redis-local.conf:/usr/local/etc/redis/redis.conf

volumes:
  pgdata_local:
